FIXME修正完了
kyainuma/rspec_app_exam pull request #1
Opened 2020-12-16 14:24 UTC by kyainuma

FIXME修正完了しましたので確認お願いします。
TODOはリファクタリング中です。

2020-12-17 03:56 UTC, yuji91 requested changes
細かい点指摘しました！

2020-12-17 03:56 UTC, yuji91 commented on spec/system/task_spec.rb
> +  include(ApplicationHelper)
ここに記載すると他のファイルで使えないので、設定ファイルに記載するようにしましょう。

2020-12-17 03:56 UTC, yuji91 commented on spec/system/task_spec.rb
> +        fill_in 'Deadline', with: task.deadline
ここ変える必要ってありますでしょうか？

2020-12-17 12:39 UTC, kyainuma commented on spec/system/task_spec.rb
> +        fill_in 'Deadline', with: task.deadline
修正前のコードでテストを通すと下記のエラーになります。
`1) Task Task編集 正常系 Taskを編集した場合、一覧画面で編集後の内容が表示されること
     Failure/Error: expect(find('.task_list')).to have_content(short_time(task.deadline))
       expected to find text "8/30 0:00" in "Task doing 12/17 21:35 Show Edit Destroy"`

上記はfactories/tasks.rb内で日付がランダムに帰ってくるので`Time.current`だと一致せず、テストが落ちると思い、上記のように修正しました。

2020-12-17 12:45 UTC, kyainuma commented on spec/system/task_spec.rb
> +  include(ApplicationHelper)
4353c37dc0c0088dc04b0a8bfd3a8fcd66e415c8 修正しました。

2020-12-17 15:02 UTC, yuji91 requested changes
2点細かい点の修正をお願いします！

2020-12-17 15:02 UTC, yuji91 commented on spec/rails_helper.rb
> +  include(ApplicationHelper)
includeの括弧は基本省略して書きますね！
```suggestion
  include ApplicationHelper
```

2020-12-17 15:02 UTC, yuji91 commented on spec/system/task_spec.rb
> +  include(ApplicationHelper)
別途記載したので、ここの記載は消しておいて頂けると！

2020-12-17 21:19 UTC, kyainuma commented on spec/rails_helper.rb
> +  include(ApplicationHelper)
fda07f4dad370f97c89c20de7cc45ed32beece1b 修正しました。

2020-12-17 21:21 UTC, kyainuma commented on spec/system/task_spec.rb
> +  include(ApplicationHelper)
35093468a26cce326211fc6b483a8427f58d4544 すいません。このコミットでまとめてしまいました。修正しました。

2020-12-17 21:30 UTC, kyainuma commented
TODO リファクタリングしたので確認お願いします。
38c712ba75d59f0d09df3b6d031480a9c626eae8 あと仕様には無いのですが、'Taskが削除されること'を`let`を使用しようとした際に、`let!`だと通り、`before`だと通らない仕組みがわからないです。
beforeだと`1) Task Task削除 正常系 Taskが削除されること
     Failure/Error: expect(Task.count).to eq 0
     
       expected: 0
            got: 1
     
       (compared using ==)`
となります。byebugで確認してもtaskは有りましたが、Viewには表示されていませんでした。
[![Image from Gyazo](https://i.gyazo.com/c1ff97b33024c2a69859da30c30e2bd5.png)](https://gyazo.com/c1ff97b33024c2a69859da30c30e2bd5)

2020-12-23 04:33 UTC, yuji91 commented
38c712b ですが、byebugで状況が確認できると思うので、何が発生しているのかを確認してみてください。
[![Image from Gyazo](https://i.gyazo.com/5cbce42ed5a46c08dfd844bb654ab905.png)](https://gyazo.com/5cbce42ed5a46c08dfd844bb654ab905)

2020-12-23 04:35 UTC, yuji91 commented
デバッグすることで事象を把握して、仮説が立てられると良いと思います。
[![Image from Gyazo](https://i.gyazo.com/a94d1b9110456a793e9e9a32fe65728b.png)](https://gyazo.com/a94d1b9110456a793e9e9a32fe65728b)

2020-12-23 07:30 UTC, kyainuma commented
38c712ba75d59f0d09df3b6d031480a9c626eae8 以下の仮説と検証の結果、`before`の場合は`expect(find('.task_list')).not_to have_content task.title`のときに`let(:task)`が遅延評価され、taskオブジェクトが新たに作られテストが失敗すると考えました。

以下仮説です。
仮説①:`before`の場合は`let`が呼び出されているのではないか？
検証:
`let(:task) { create(:task, project_id: project.id, title: "let") }`
`before { create(:task, project_id: project.id, title: "before") }`
として検証
結果:添付写真①でtitleがletになっているので`let`が呼び出されていることが確認できました。


仮説②:上記の`let`は`expect(find('.task_list')).not_to have_content task.title`で呼び出されているのではないか？
検証:`expect(find('.task_list')).not_to have_content "before" # task.title`として検証
結果:添付写真②で`Task.count`が0だったので上記の検証タイミングで呼ばれていることを確認

`let!(:task)`にすることで先に評価し、`expect(find('.task_list')).not_to have_content task.title`のタイミングで`let`が評価されないのでテストが通るようになると考えました。

2020-12-23 07:34 UTC, kyainuma commented
添付写真①:titleがletになっているのでletが呼び出されていることが確認
[![Image from Gyazo](https://i.gyazo.com/9ec6d745027865494bf98ccfe669ac6c.png)](https://gyazo.com/9ec6d745027865494bf98ccfe669ac6c)

添付写真②:Task.countが0だったので上記の検証タイミングで呼ばれていることを確認
[![Image from Gyazo](https://i.gyazo.com/e05c67d7ae51aafba31d4fd1f794d4c6.png)](https://gyazo.com/e05c67d7ae51aafba31d4fd1f794d4c6)

2020-12-23 07:49 UTC, yuji91 requested changes
細かい1点コメントしました！

2020-12-23 07:49 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
associationが設定されていれば、この指定は要らないような気がします。
```suggestion
  let(:task) { create(:task) }
```

2020-12-23 07:58 UTC, kyainuma commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
fc22678c073dd0bc67f65b42c53fd26e50fc7c78 修正しました。

2020-12-23 22:52 UTC, kyainuma commented
テスト実行結果
[![Image from Gyazo](https://i.gyazo.com/e2a86f7880bc9e3d7a3046ba7259facc.jpg)](https://gyazo.com/e2a86f7880bc9e3d7a3046ba7259facc)

2020-12-24 01:40 UTC, yuji91 approved these changes
LGTMです！

2020-12-24 08:26 UTC, merged